### ISSUE TITLE
Tooltip has low z-index

### ISSUE THREAD

**Issue by nainardev** [pastelsky/bundlephobia#296]
Hides behind bar chart. Unable to read
![Screenshot (115)](https://user-images.githubusercontent.com/59839368/74624410-5440b280-516e-11ea-9532-664013af8418.png)

**Comment by limahatzl** [comment]
I believe this issue was fixed
I can't replicate the same... both OS: mac, windows and different browsers looks good to me...

**Comment by nainardev** [comment]
Happens when I hover over the tree icon

**Comment by pastelsky** [comment]
I don't see this happen any more –
https://github.com/pastelsky/bundlephobia/pull/314#issuecomment-687608905

@nainardev could you close this if it's fixed, or post some screenshots so I could reproduce it if not?

**Comment by nainardev** [comment]
I'll update soon

**Comment by keul** [comment]
I still see this (Firefox 82 on MacOS)

![Schermata 2020-11-04 alle 17 39 08](https://user-images.githubusercontent.com/284924/98139748-d3287780-1ec4-11eb-9fa2-6471c48f402d.png)

**Comment by nainardev** [comment]
Me too in Firefox Dev

**Comment by keul** [comment]
Spent few minutes debugging the issue (just because I was curious about the full CSS implementation! I was not aware of `attr()` 😱).

The tooltip is a css content with a position absolute inside a position relative main element (the vertical bar) so it's normal that it is under elements defined after it.

Raising the z-index on the focused element fix the issue.

![zindex](https://user-images.githubusercontent.com/284924/98217211-7b345400-1f4a-11eb-822c-4dcdda17e770.gif)

**Comment by roansong** [comment]
Can confirm that I am experiencing this as well, with the side-effect-free icon tooltip:
![image](https://user-images.githubusercontent.com/14807642/117940045-f36c3f80-b308-11eb-8f43-ea253f623efa.png)

**Comment by himynameisdave** [comment]
Hate to be the one to report that this is still an issue, but this is still an issue:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/4298089/134748636-7b6592fd-ec37-4087-9b17-7de4ced36b19.png">


Browser: Firefox 92


Happy to open a PR ([looks like](https://github.com/pastelsky/bundlephobia/issues/296#issuecomment-722229025) @keul has already solved this) if there isn't one already!
